<a href="https://colab.research.google.com/github/jcdevaney/gawayneLessons/blob/main/week1/Some%20Python%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries and give them abbreviations

In [1]:
import numpy as np

Create an array of 3 elements from 1 to 3

In [2]:
a = np.arange(1,4)
print(a)

[1 2 3]


Create an array of 3 elements from 5 to 9, increasing by 2s

In [3]:
b = np.arange(5,11,2)
print(b)

[5 7 9]


Create an array of 3 elements from 11 to 7, decreasing by 2s

In [4]:
c = np.arange(11,5,-2)
print(c)

[11  9  7]


Index into a

In [5]:
a[1:3]

array([2, 3])

Add elements in array a to array b

In [6]:
a + b

array([ 6,  9, 12])

Subtract elements in array b from array a

In [7]:
a - b

array([-4, -5, -6])

Multiply elements in array a with array b

In [8]:
a * b

array([ 5, 14, 27])

Divide elements in array a by the elements in array b

In [9]:
a / b

array([0.2       , 0.28571429, 0.33333333])